### ISSUE TITLE
Windows version does not find node.exe

### ISSUE THREAD

**Issue by duncangroenewald** [rgl/playwright-standalone#1]
it seems the windows build does not set the path to find node.exe - I would suggest adding the following to the playwright.cmd

set PATH=%SCRIPT_PATH%\.node;%PATH%

/* build.ps1 */
...
Set-Content -Encoding ascii -Path playwright.cmd -Value @'
@echo off
set SCRIPT_PATH=%~dp0
set PATH=%SCRIPT_PATH%\.node;%PATH%
set PLAYWRIGHT_BROWSERS_PATH=%SCRIPT_PATH%\node_modules\playwright-core\.local-browsers
call %SCRIPT_PATH%\node_modules\.bin\playwright.cmd %*
'@

**Comment by rgl** [comment]
Fixed in https://github.com/rgl/playwright-standalone/releases/tag/v0.0.3.

Thank you!
